# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos73-min.box"
  config.vm.box_url = "../centos73-min.box"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.hostname = "pet"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb = config.vm.hostname

  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = 'ansible/provision.yml'
#    ansible.verbose = 'vv'
#  end
end
