# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos73-min.box"
    config.vm.box_url = "/home/student/cm/ansible/centos73-min.box"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.hostname = "pet"

  config.vm.provider "virtualbox" do |vb|
    vb = config.vm.hostname
  end
end
