---
- name: Install NGINX
  yum:
    name: nginx
    state: installed

- name: replace nginx.conf with aproriate
  template:
    src: ./nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0744
  notify: restart nginx

#- name: create directories for ssl certificates
#  file:
#    path: /etc/nginx/ssl
#    state: directory
#
#- name: copy TLS key
#  copy:
#    src: ./nginx.key
#    dest: "{{ key_file }}"
#    owner: root
#    mode: 0600
#  notify: restart nginx
#
#- name: copy TLS certificate
#  copy:
#    src: ./nginx.crt
#    dest: "{{ cert_file }}"
#  notify: restart nginx

- name: enable and start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon-reload: yes
